'use client';
import {useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,CheckCircle2,LockKeyhole,LoaderCircle} from 'lucide-react';
import {Choice,CheckField} from './form-controls';
import {MARKETING_COPY,validateLead} from '@/lib/validation';
import {identifySubmission} from '@/lib/submission';
import {site} from '@/lib/site';
export function EnquiryForm(){
 const [interest,setInterest]=useState('Financial & Estate Review'),[method,setMethod]=useState('email'),[marketing,setMarketing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{reference:string;delivery:string}|null>(null);
 const identity=useRef({fingerprint:'',id:''}),errorRef=useRef<HTMLDivElement>(null);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{const lead=identifySubmission(identity.current,validateLead({requestId:crypto.randomUUID(),name:data.get('name'),email:data.get('email'),phone:data.get('phone')??'',message:data.get('message')??'',website:data.get('website')??'',interest,contactMethod:method,callback:method!=='email',marketingEmail:marketing}));const response=await fetch('/api/enquiry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lead)});const json=await response.json() as {error?:string;reference:string;delivery:string};if(!response.ok)throw new Error(json.error||'Unable to send your request.');setResult(json);}catch(err){setError(err instanceof Error?err.message:'Unable to send your request.');setTimeout(()=>errorRef.current?.focus(),0);}finally{setBusy(false);}}
 if(result)return <div className="success-panel" role="status"><CheckCircle2 size={42} strokeWidth={1.3}/><p className="eyebrow">YOUR NEXT STEP</p><h2>Your review request<br/><em>has been saved.</em></h2><p>Reference: <strong>{result.reference}</strong>. An appointment is only confirmed once the details have been agreed.</p>{result.delivery==='not-configured'?<p className="notice">This is a private preview. Adviser email notifications are not connected, so please use sample details. To contact Sim now, use the Instagram profile below.</p>:result.delivery==='failed'?<p className="notice">Your request was saved, but the notification could not be delivered. Please contact Sim directly if your enquiry is time-sensitive.</p>:<p>Your request has been sent to the adviser’s inbox. Keep your reference for any follow-up.</p>}<a href={site.instagram} className="text-link" target="_blank" rel="noreferrer">Visit @bettercallsimuk <ArrowUpRight size={17}/></a><Link href="/the-plan" className="button">Explore the planning approach <ArrowUpRight size={17}/></Link></div>;
 return <form onSubmit={submit} className="enquiry-form"><div className="form-heading"><span>LET’S START WITH YOU</span><h2>What’s on your mind?</h2><p>Share a few details. There’s no need to have all the answers.</p></div>{site.preview&&<p className="notice">Private preview — use sample details. No appointment will be automatically booked.</p>}<div ref={errorRef} tabIndex={-1} role={error?'alert':undefined}>{error&&<p className="form-error">{error}</p>}</div><div className="form-grid"><div className="field"><label htmlFor="name">Your name</label><input className="field-input" autoComplete="name" id="name" name="name" required maxLength={100} placeholder="Full name"/></div><div className="field"><label htmlFor="email">Email address</label><input className="field-input" id="email" name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com"/></div></div><Choice id="interest" label="What would you like to explore?" value={interest} onChange={setInterest} options={['Financial & Estate Review','Estate Planning','Financial Advice','Property Finance','Not sure yet'].map(v=>({value:v,label:v}))}/><div className="form-grid"><Choice id="contact-method" label="How would you prefer to hear back?" value={method} onChange={setMethod} options={[{value:'email',label:'Email'},{value:'phone',label:'Telephone'},{value:'whatsapp',label:'WhatsApp'}]}/><div className="field"><label htmlFor="phone">Telephone {method==='email'?'(optional)':''}</label><input className="field-input" id="phone" name="phone" type="tel" autoComplete="tel" required={method!=='email'} maxLength={30} placeholder="Your contact number"/></div></div><div className="field"><label htmlFor="message">Anything you’d like to add? <span>(optional)</span></label><textarea className="field-input" id="message" name="message" rows={4} maxLength={1000} placeholder="A little about what you’d like to discuss…"/><p className="field-hint">Please leave out account numbers, health details and other confidential information.</p></div><div className="honeypot" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div><CheckField id="marketing-email" label={MARKETING_COPY} checked={marketing} onChange={setMarketing}/><p className="privacy-copy"><LockKeyhole size={14}/> Your details are used to handle this request. Marketing is optional. <Link href="/privacy">Privacy notice</Link></p><button disabled={busy} className="button form-submit" type="submit">{busy?'Sending your request…':'Request Your Financial & Estate Review'}{busy?<LoaderCircle className="spin" size={17}/>:<ArrowUpRight size={17}/>}</button><p className="field-hint">The appointment format, scope and any fee will be agreed before you proceed.</p></form>
}
